# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20151201_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Author'),
        ),
    ]
