# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20151206_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['author_last', 'author_first', 'author_middle']},
        ),
        migrations.AlterModelOptions(
            name='quotegenre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='sourcetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='source',
            name='sort_title',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_last',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_middle',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
